## INTRODUCCIÓN A NUMPY

Cuando un calculo debe repetirse para un conjunto de valores de entrada, es natural y ventajoso representar esos datos como arrays. Numpy es una potente libreria de python que manipula matrices , vectores y arrays. Esta libreria es ampliamente usada para el procesamiento de imagenes (PDI) , intelegencia artificial (IA) , Sistemas de Control ,etc.<br>
Sirve como base para el desarrollo de otras librerias o framework de python como : ***scikit learn , Tensorflow , pytorch , etc***.

## IMPORTACIÓN DEL MÓDULO Y VERIFICANDO LA VERSIÓN

In [1]:
import numpy as np

In [10]:
a=np.array([[2,3,4]])
b=np.repeat(a,3,axis=0)
b

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [13]:
s=np.eye(3)
s

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.sum(s,axis=0,dtype='int32')

array([1, 1, 1])

In [23]:
print(np.__version__)

1.20.3


In [156]:
# DOCUMENTACIÓN
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\HP\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\hp\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x =

## CURIOSIDADES CON NUMPY

* ### ELEMENTO NULO

In [4]:
# EL ARREGLO TIENE POR LO MENOS UN ELEMENTO NULO? -> True or False
a=np.array([1,3,5,7])
c=np.all(a)
print(c) # Nos da verdad porque ninguno de los elementos son cero
a[-1]=0
print(np.all(a)) # esto indica que el arreglo tiene por lo menos un cero

True
False


* ### ELEMENTO DISTINTO DE CERO

In [161]:
# HAY ALGÚN ELEMENTO DISTINTO DE CERO? -> True or False
a1=[0,0,0,0]
a2=np.array([0,0,1,0])
print(np.any(a1))
print(np.any(a2))

False
True


* ### VERIFICACIÓN SI LOS ELEMENTOS SON FINITOS, INFINITOS O NULOS 

In [7]:
# VERIFICACIÓN DE ELEMENTOS SI SON FINITOS O INFINITOS
a=np.array([0,1,2,np.nan,np.inf,-np.inf])
m1=np.isfinite(a) 
print(m1,' -> ',type(m1))

m2=np.isinf(a)
print(m2,' -> ',type(m2))

m3=np.isnan(a)
print(m3,' -> ',type(m3))

[ True  True  True False False False]  ->  <class 'numpy.ndarray'>
[False False False False  True  True]  ->  <class 'numpy.ndarray'>
[False False False  True False False]  ->  <class 'numpy.ndarray'>


* ### VERIFICAR SI CADA ELEMENTO ES UN REAL, ESCALAR O COMPLEJO

In [11]:
a=np.array([1,2,-1+2j,3,2j])
print(np.iscomplex(a))
print(np.isreal(a))
b=5.5
print(np.isscalar(b))
print(np.isscalar(a))

[False False  True False  True]
[ True  True False  True False]
True
False


* ### GRADO DE IGUALDAD CON TOLERANCIA

In [13]:
print(np.allclose([2,3],[2.0000001,3.0]))
print(np.allclose([1e10,1e-7],[1.00001e10,1e-8]))

True
False


* ### OPERADORES RELACIONALES EN UN ' ndarray '

In [74]:
a=np.array([5,7,0])
b=np.array([-2,10,0])
# el orden imponrta -> (a,b) != (b,a)
print('se interpreta como: todos los elementos de',a,'son menores que',b,' -> ',np.less(a,b)) 
print('\nse interpreta como: todos los elementos de',a,
      'son menores o igual que',b,' -> ',np.less_equal(a,b))
print('\nse interpreta como: todos los elementos de',a,
      'son mayores que',b,' -> ',np.greater(a,b))
print('\nse interpreta como: todos los elementos de',a,
      'son mayores o igual que',b,' -> ',np.greater_equal(a,b))

se interpreta como: todos los elementos de [5 7 0] son menores que [-2 10  0]  ->  [False  True False]

se interpreta como: todos los elementos de [5 7 0] son menores o igual que [-2 10  0]  ->  [False  True  True]

se interpreta como: todos los elementos de [5 7 0] son mayores que [-2 10  0]  ->  [ True False False]

se interpreta como: todos los elementos de [5 7 0] son mayores o igual que [-2 10  0]  ->  [ True False  True]


* ### GRADO DE COMPARACIÓN

In [90]:
a=np.array([1,2,3,3])
b=np.array([1,2,3,3.0000001])
print(np.isclose(a,b)) # nos soporta una tolerancia de 1e-8

# cambiando la tolerancia
print(np.isclose(a,b,rtol=1e-9))

[ True  True  True  True]
[ True  True  True False]


## COMPARANDO LISTAS Y ' ndarrays ' DE NUMPY :

In [1]:
# Las listas no realizan operaciones de elemento a elemento.
# El signo '+' para las listas sirven para concatenar.
a=[1,2,3,4,5]
b=[10,11,12,13,14]
print(a+b)

[1, 2, 3, 4, 5, 10, 11, 12, 13, 14]


In [2]:
# Si quisiera hacer alguna operación elemento a elemento tengo que recorrerlos.
# PRIMER MÉTODO
r=[]
for i in range(len(a)):
    f=a[i]+b[i]
    r.append(f)
print(r) 

[11, 13, 15, 17, 19]


In [2]:
# SEGUNDO MÉTODO
w=[]
for x,y in zip(a,b):
    w.append(x+y)
print(w) 

[11, 13, 15, 17, 19]


In [6]:
# los ndarray si realizan operaciones elemento a elemnto sin recorrerlas.
# OPERACIONES VECTORIZADAS
a=np.array([1,2,3,4,5])
b=np.array([10,11,12,13,14])
print(a+b)

[11 13 15 17 19]


## CREANDO VARIOS ' ndarrays '

In [4]:
a=np.array([1,2,3,4])
print(type(a))
print(type(a[0]))
print(a[-3:])
print(a.dtype) # Me perimite ver el tamaño de cualquiera de los items del ndarray
print(a.itemsize)

<class 'numpy.ndarray'>
<class 'numpy.int32'>
[2 3 4]
int32
4


In [10]:
c=np.array([1,5,3.0,4])
print(c)
print(type(c))
print(c.dtype)

[1. 5. 3. 4.]
<class 'numpy.ndarray'>
float64


In [93]:
# CREACIÓN DE ARREGLOS
a=np.zeros(10)
print('Arreglo con 10 ceros:',a)
b=np.ones(10)
print('Arreglo con 10 unos:',b)
c=np.ones(10)*7
print('Arreglo con 10 sietes:',c)

Arreglo con 10 ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Arreglo con 10 unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Arreglo con 10 sietes: [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


In [98]:
a=np.arange(20,51)
print('Números entre 20 y 50:',a)
b=np.arange(20,51,2)
print('\nNúmeros pares entre 20 y 50:',b)

Números entre 20 y 50: [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]

Números pares entre 20 y 50: [20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [5]:
# MATRIZ IDENTIDAD
matrix=np.identity(3)
matrix=np.eye(3)
print('la matriz identidad tiene como diagonal principal solo unos.')
print(matrix)

# NÚMEROS ALEATORIOS ENTRE 0 Y 1(excluido el 1)
aleatorio=np.random.random()
print('\nUn número aleatorio entre 0 y 1(excepto este)=',round(aleatorio,3))
print(type(aleatorio))

# 
estandar=np.random.normal(0,1,10)
print('\nTenemos 10 números aleatorios que siguen una distribución normal estandar:',estandar)

la matriz identidad tiene como diagonal principal solo unos.
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Un número aleatorio entre 0 y 1(excepto este) 0.177
<class 'float'>

Tenemos 10 números aleatorios que siguen una distribución normal estandar: [-1.07239954  0.23836099 -1.03971041  0.0861474  -1.25046403 -1.08899405
  0.90621952 -1.86127671 -0.38060369  1.18876728]


In [119]:
s=np.arange(16,55)
print('vector entre 15 y 55, excepto estos límites:',s)

vector entre 15 y 55, excepto estos límites: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [7]:
# Me permite crear valores aleatorios enteros
w=np.random.randint(3,8,9)
print(w)

[6 4 5 6 3 5 7 4 5]


In [68]:
n1=np.random.randint(1,100,12)
print(n1)

[44 69 44 66  7 71 21 98 79 84 27 43]


In [60]:
print('\n----------- LA MATRIZ ORIGINAL -------------\n')
s=np.random.random((3,5))
print(s,' -> ',s.ndim)
z=s.flatten()
print('\n',z,' -> ',z.ndim)
z=s.ravel()
print('\n',z,' -> ',z.ndim)
z=s.flatten(order='F')
print('\n',z,' -> ',z.ndim)
print('\n----------- TRANSPUESTA DE LA MATRIZ ORIGINAL -------------\n')
print(np.transpose(s))
print('\n',s.swapaxes(0,1))


----------- LA MATRIZ ORIGINAL -------------

[[0.37445142 0.24943026 0.85135975 0.47871933 0.72484195]
 [0.60203577 0.76198459 0.99767622 0.41810983 0.68314412]
 [0.17222197 0.08289198 0.53099134 0.77256063 0.90522771]]  ->  2

 [0.37445142 0.24943026 0.85135975 0.47871933 0.72484195 0.60203577
 0.76198459 0.99767622 0.41810983 0.68314412 0.17222197 0.08289198
 0.53099134 0.77256063 0.90522771]  ->  1

 [0.37445142 0.24943026 0.85135975 0.47871933 0.72484195 0.60203577
 0.76198459 0.99767622 0.41810983 0.68314412 0.17222197 0.08289198
 0.53099134 0.77256063 0.90522771]  ->  1

 [0.37445142 0.60203577 0.17222197 0.24943026 0.76198459 0.08289198
 0.85135975 0.99767622 0.53099134 0.47871933 0.41810983 0.77256063
 0.72484195 0.68314412 0.90522771]  ->  1

----------- TRANSPUESTA DE LA MATRIZ ORIGINAL -------------

[[0.37445142 0.60203577 0.17222197]
 [0.24943026 0.76198459 0.08289198]
 [0.85135975 0.99767622 0.53099134]
 [0.47871933 0.41810983 0.77256063]
 [0.72484195 0.68314412 0.90522

## RECORRIENDO UNA MATRIZ BIDIMENSIONAL

In [9]:
d=np.arange(1,13).reshape(4,3);print('MATRI DE 4 X 3')
print(d,'\n')
for i in np.nditer(d):
    print(i,end=' ')
print('\n')      
for i in np.nditer(d,order='C'):
    print(i,end=' ')
print('\n')    
for i in np.nditer(d,order='F'):
    print(i,end=' ')
print('\n')    
for i in np.nditer(d,order='K'):
    print(i,end=' ')    

MATRI DE 4 X 3
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

1 2 3 4 5 6 7 8 9 10 11 12 

1 2 3 4 5 6 7 8 9 10 11 12 

1 4 7 10 2 5 8 11 3 6 9 12 

1 2 3 4 5 6 7 8 9 10 11 12 

## SUMANDO LOS ELEMENTOS DE UNA MATRIZ BIDIMENSIONAL

In [64]:
d=np.arange(1,13).reshape(4,3);print('MATRI DE 4 X 3')
print(d)
suma=0
for i in np.nditer(d):
    suma=suma+i
print('\nLa suma de los elementos de la matriz es:',suma) 
print('La suma es:',(np.sum(d)))
print('La suma por columnas de la matriz:',np.sum(d,axis=0))
print('La suma por filas de la matriz:',np.sum(d,axis=1))

MATRI DE 4 X 3
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

La suma de los elementos de la matriz es: 78
La suma es: 78
La suma por columnas de la matriz: [22 26 30]
La suma por filas de la matriz: [ 6 15 24 33]


## ATRIBUTOS QUE TIENE UN ' ndarray ' DE NUMPY:

In [10]:
# Importamos numpy con un alias
# Tenemos un vector o una matriz de una sola dimensión o eje
r=np.arange(9)
print(r)
print(id(r))

[0 1 2 3 4 5 6 7 8]
1686632551216


In [14]:
# 6. -> representa un numero flotante (6.0)
# Tenemos un matriz de 2 x 3 o de 2 dimensiones
b=np.array([[9.0,9.1,4.0],
            [3.0,5.0,1.0]])
print(b)

[[9.  9.1 4. ]
 [3.  5.  1. ]]


In [91]:
e=np.array([3,5,8,8])
#atributos para la matriz unidimensional
print(e.shape) # para una sola fila indica el numero de elementos
print(e.dtype) # tipo de datos de cada elemento de la fila en bits(todos pesan lo mismo)
print(e.size) # numero de elementos
print(e.ndim) # indica la dimensión del vector
print(e.nbytes) # indica el # de bytes de todo el vector
print(e.itemsize) # indica el número de bits de cada elemento

(4,)
int32
4
1
16
4


In [17]:
# Matriz bidimensional
e=np.array([[3,5,8,8],
            [3,5,9,2]])

#atributos para la matriz bidimensional
print(e.shape) # para matrices multidimencionales
# shape siempre devuelve una tupla -> (# de filas,# de columnas)
print(e.dtype)
print(e.size)
print(e.ndim)
print(e.nbytes) # el numero de bytes de toda la matriz

(2, 4)
int32
8
2
32


## CAMBIANDO LOS TIPOS DE DATOS DENTRO DE UN ' ndarray '

In [55]:
# int->entero 4 bytes para windows
# float -> flotante 8 bytes para windows
# Para ajustar el tamaño o la longitud de los datos definir los tipos con los siguientes tipos Numpy:
# np.int8: (1 byte) - Para enteros entre -128 y 127.->(0,256)
# np.int16: (2 bytes) - Para enteros entre -32768 y 32767.
# np.int32: (4 bytes) - Para enteros entre -2147483648 y 2147483647.
# np.int64: (8 bytes) - Para números enteros entre -9223372036854775808 y 9223372036854775807

In [21]:
# MATRIZ UNIDIMENSIONAL 
v=np.array([4.1,5])
print(v)
print(v.dtype)
v=np.array([4.1,5], dtype='complex')
print(v)

[4.1 5. ]
float64
[4.1+0.j 5. +0.j]


In [26]:
# MATRIZ BIDIMENSIONAL O MULTIDIMENSIONAL
d=np.array([[33,6,8],
            [3,6,9]])
print(d,'\n')
print(d.dtype,'\n')
d=np.array([[33,6,8],[3,6,9]],dtype=np.int16)
print(d,'\n')
print(d.dtype)

[[33  6  8]
 [ 3  6  9]] 

int32 

[[33  6  8]
 [ 3  6  9]] 

int16


In [173]:
# MATRIZ BIDIMENSIONAL O MULTIDIMENSIONAL
m=np.array([[1,9,5],[7,0,2],[-4,8,3]],'int16')
print(m,'\n')
print(m.dtype,'\n')
#n=np.array([[1,9,5],[7,0,2],[4,8,3]],dtype='float')
n=np.array([[1,9,5],[7,0,2],[4,8,3]],dtype='float')
print(n,'\n')
print(n.dtype,'\n')
n=np.array([[1,9,5],[7,0,2],[4,8,3]],'complex')
print(n,'\n')
print(n.dtype,'\n')

[[ 1  9  5]
 [ 7  0  2]
 [-4  8  3]] 

int16 

[[1. 9. 5.]
 [7. 0. 2.]
 [4. 8. 3.]] 

float64 

[[1.+0.j 9.+0.j 5.+0.j]
 [7.+0.j 0.+0.j 2.+0.j]
 [4.+0.j 8.+0.j 3.+0.j]] 

complex128 



## OBTENER Y COLOCAR LOS ELEMENTOS

vamos a trabajar con 1D y 2D, pero pero siempre obtendremos solo un valor o en su defecto una fila o columna

## INDEX Y SLICING

In [174]:
# MATRIZ UNIDIMENSIONAL O VECTOR
s=np.array([4,6,9,3,1,2,10])
print(s,'\n')
print('OBTENEMOS UN SOLO VALOR O ELEMENTO DE LA MATRIZ FILA O VECTOR','\n')
# este proceso tambien se llama indexacion
print(s[0])
print(s[4])
print(s[-1])
print(s[-5])
print('------------------------------------------------------------------------')
print('\n','AHORA OBTENDREMOS REBANADAS O CORTES DEL VECTOR','\n')
print(s[0:5])
print(s[2:4])
print(s[2:-2])
print(s[-3:-1])
print(id(s))

[ 4  6  9  3  1  2 10] 

OBTENEMOS UN SOLO VALOR O ELEMENTO DE LA MATRIZ FILA O VECTOR 

4
1
10
9
------------------------------------------------------------------------

 AHORA OBTENDREMOS REBANADAS O CORTES DEL VECTOR 

[4 6 9 3 1]
[9 3]
[9 3 1]
[1 2]
2332933241520


In [175]:
# Pero tambien podemos insertar elementos
s=np.array([4,6,9,3,1,2,10])
print(id(s))
s[0]=5
print(s)
print(id(s))
print(type(s))
print('\n','Podemos insertar tambien en una rebanada','\n')
s[1:3]=25
print(s)
print(id(s))

2332954825136
[ 5  6  9  3  1  2 10]
2332954825136
<class 'numpy.ndarray'>

 Podemos insertar tambien en una rebanada 

[ 5 25 25  3  1  2 10]
2332954825136


In [31]:
# PARA UNA MATRIZ BIDIMENSIONAL O MULTIDIMENCIONAL
z=np.array([[4,6,9,3],
            [5,1,2,10],
            [3,5,7,12]])
print(z,'\n')
print(id(z),'\n')
# Obtenemos la transpuesta
y=z.T
print(y,'\n')
print(id(y),'\n')
# Obtenemos las filas
print(z[0],'\n')
print(z[2],'\n')
# Obtenemos las columnas
print(y[0],'\n')
print(y[2],'\n')
# Si desemos obtener los elementos
print(z[0][0],'\n') # z[0,0]
print(z[2][1],'\n') # z[2,1]
print(z[2,3])

[[ 4  6  9  3]
 [ 5  1  2 10]
 [ 3  5  7 12]] 

1851484500304 

[[ 4  5  3]
 [ 6  1  5]
 [ 9  2  7]
 [ 3 10 12]] 

1851484500592 

[4 6 9 3] 

[ 3  5  7 12] 

[4 5 3] 

[9 2 7] 

4 

5 

12


In [32]:
z[0][0]=19393
print(z)

[[19393     6     9     3]
 [    5     1     2    10]
 [    3     5     7    12]]


ahora rebanaremos o cortaremos matrices de 2D

## SLICING e INDEX

In [ ]:
# Tambien utilizamos corchetes e involucramos almenos dos puntos

In [33]:
# EJERCICIO N°1
w=np.array([ [0 ,1 ,2 ,3 ,4 ,5],
             [10,11,12,13,14,15],
             [20,21,22,23,24,25],
             [30,31,32,33,34,35],
             [40,41,42,43,44,45],
             [50,51,52,53,54,55]])
print(w.shape,'\n')
print(w,'\n')
print(w[:1,3:5],'\n')
print(w[4:6,4:6],'\n')
print(w[:6,2:3])

(6, 6) 

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]] 

[[3 4]] 

[[44 45]
 [54 55]] 

[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]


In [36]:
# EJERCICIO N°2
# formamos la matriz
d=np.arange(25).reshape(5,5)
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [38]:
red1=d[0:5,1:2]
red2=d[0:5,3:4]
red=d[0:5,1:4:2]
yellow=d[4] #d[4:5,0:5]
blue1=d[1:2,0:3:2]
blue2=d[3,:3:2]
blue=d[1:4:2,0:3:2]
print(red1,'\n')
print(red2,'\n')
print(red,'\n')
print(yellow,'\n')
print(blue1,'\n')
print(blue2,'\n')
print(blue,'\n')

[[ 1]
 [ 6]
 [11]
 [16]
 [21]] 

[[ 3]
 [ 8]
 [13]
 [18]
 [23]] 

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]] 

[20 21 22 23 24] 

[[5 7]] 

[15 17] 

[[ 5  7]
 [15 17]] 



## COPIA

In [40]:
# Tenemos un vector
a=np.array([1,2,3,4])
print(a,'\n')
print(id(a),'\n')
b=a[:2]
print(b,'\n')
print(id(b),'\n')
b[1]=45
print(b,'\n')
print(a,'\n')
print(np.shares_memory(a,b))


[1 2 3 4] 

1851484502800 

[1 2] 

1851484500880 

[ 1 45] 

[ 1 45  3  4] 

True


In [41]:
a=np.array([1,2,3,4])
print(a,'\n')
b=a[:2]
b=a.copy()
print(b,'\n')
b[0]=444
print(b,'\n')
print(a,'\n')
print(np.shares_memory(a,b))

[1 2 3 4] 

[1 2 3 4] 

[444   2   3   4] 

[1 2 3 4] 

False


In [ ]:
# SE LLAMA INDEXACION ELEGANTE, INDEXACIÓN BOLEANA O ENMASCARAMIENTO

## INDEXACIÓN ELEGANTE EN 2D

In [42]:
# TEORIA

r=np.array([[3,5,6],
            [6,8,9],
            [3,5,9],
            [10,5,6]])
print(r,'\n')
print(r[2:4,0:2],'\n') # utilizando el slicing o corte
print(r[[2,3],0:2],'\n') # utilizando la indexacion elegante
print(r[2:4,[0,1]],'\n') # utilizando la indexacion elegante


[[ 3  5  6]
 [ 6  8  9]
 [ 3  5  9]
 [10  5  6]] 

[[ 3  5]
 [10  5]] 

[[ 3  5]
 [10  5]] 

[[ 3  5]
 [10  5]] 



# MASCARA CON BOLEANOS

In [43]:
# LO QUE PERMITE LA INDEXACION ELEGANTE
# Hacemos uso de una mascara: son valores que ocupan ciertas ubicaciones.
# esas ubicaciones primero pasan por un filtro o validacion
# Se muestra internamente el funcionamiento de la mascara

r=np.array([0,10,20,30,40,50,60,70])
mask1=np.array([0,1,1,0,1,0,1,0],dtype='bool')
mask2=np.array([False,True,True,False,True,False,True,False])
print(r,'\n')
print(mask1,'\n')
print(r[mask1],'\n')
print(mask2,'\n')
print(r[mask2],'\n')

# Generalmente la vemos de esta forma
print(r[r>36]) #r=np.array([0,10,20,30,40,50,60,70])

[ 0 10 20 30 40 50 60 70] 

[False  True  True False  True False  True False] 

[10 20 40 60] 

[False  True  True False  True False  True False] 

[10 20 40 60] 

[40 50 60 70]


## EJEMPLO

In [50]:
q=np.arange(60,step=10).reshape(6,1) + np.arange(6,step=1)
print(q,'\n')

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]] 



In [51]:
# Armamos la MATRIZ

q=np.arange(60,step=10).reshape(6,1) + np.arange(6,step=1)
print(q,'\n')
rows=[0,1,4,3,2]
cols=[1,4,3,5,2]
# .reshape(6,1)
#np.arange(6,step=1)
# Indexacion elegante

print(q[rows,cols],'\n')  # print(q[[0,1,4,3,2],cols=[1,4,3,5,2]],'\n')

# Con esto podemos visualizar que sucede internamente con la indexacion elegante

print(list(zip(rows,cols)),'\n')

# otro ejemplo:

# 10->(1,0)  33->(3,3)  44->(4,4)  52->(5,2)  0->(0,0)
print(q[[1,3,4,5,0],[0,3,4,2,0]])


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]] 

[ 1 14 43 35 22] 

[(0, 1), (1, 4), (4, 3), (3, 5), (2, 2)] 

[10 33 44 52  0]


In [56]:
# EJERCICIO N°1

# MATRIZ ORIGINAL

s=np.arange(60,step=10).reshape(6,1)+np.arange(6,step=1)
print(s,'\n')

# al realizar una indexacion elegante se copia porciones y/o rebanadas de la matriz original

print(s[[0,1,2,3,4],[1,2,3,4,5]],'\n') # tipo indexacion elegante, NARANJA
print(s[3:,[0,2,5]],'\n') # no sciling ya que no hay un patron, AZUL 
print('--------------------------------------------------------------')

# COMPROVAMOS SI SE REALIZO UNA COPIA

v=s[[0,1,2,3,4],[1,2,3,4,5]]
print('\n',v,'\n')
print(id(s),'\t',id(v),'\n')
print(np.shares_memory(s,v),'\n')
print(s[[0,2,5],[2]],'\n') # color ROJO, primera forma
mask=np.array([1,0,1,0,0,1],dtype='bool')
print(s[mask,[2]]) # color ROJO, segunda forma




[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]] 

[ 1 12 23 34 45] 

[[30 32 35]
 [40 42 45]
 [50 52 55]] 

--------------------------------------------------------------

 [ 1 12 23 34 45] 

1851484542896 	 1851484542608 

False 

[ 2 22 52] 

[ 2 22 52]


In [57]:
# DIAGINAL DE UNA MATRIZ

d=np.diag(s)
print(d,'\n')
d=np.diag(s,1)
print(d,'\n')
d=np.diag(s,2)
print(d)

[ 0 11 22 33 44 55] 

[ 1 12 23 34 45] 

[ 2 13 24 35]


In [58]:
# EJERCICIO N°2

# ARMAMOS LA MATRIZ
u=np.arange(25).reshape(5,5)
print(u,'\n')


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 



In [ ]:
# aplicamos la funcion diagonal
# PRIMERA FORMA
w=np.diag(u,1)
print(w,'\n')

# 10->(2,1)  6->(1,1)  3->(0,3)  19->(3,4)
print(u[[2,1,0,3],[0,1,3,4]])

In [59]:
# TENER VALIDACIONES

t1=u[u%3==0] # multiplos de 3
t2=u[u%2!=0] # numeros impares
t3=u[u%2==0] # numeros pares
print(t1,'\n')
print(t2,'\n')
print(t3,'\n')

[ 0  3  6  9 12 15 18 21 24] 

[ 1  3  5  7  9 11 13 15 17 19 21 23] 

[ 0  2  4  6  8 10 12 14 16 18 20 22 24] 



In [ ]:
# Haciendo uso de una mascara, entonces trabajemos con los boleanos
# Procedimiento para la mascara

print(u%3==0,'\n')
e= u%3==0
print(e,'\n')
print(u[e],'\n')

print(u[u%3==0]) # forma directa

## FUNCIONES QUE CREAN MATRICES

In [ ]:
# Ahora ya no habra que crear nuestras propias matrices y usarlas.
# Sino que ahora usaremos matrices ya creadas y las usaremos

In [ ]:
s=np.array([2,3,4.,3])
print(s.dtype,'\n')
m=np.array([2,3,4.,3],dtype='int32')
print(m.dtype)


In [ ]:
# Orden de jerarquia
# bool < int < float < complex  ->(se duplica la presición)

## ARANGE

In [ ]:
# Signidfica ranfo de una MATRIZ, es como el generador de funciones range()

In [ ]:
l=list(range(0,6,2))
print(l)

In [ ]:
n4=np.arange(100,200,10)
print(n4)

In [128]:
q=np.arange(9)
print(q,'\n')
q=np.arange(9,18)
print(q,'\n')
q=np.arange(9,18,1.5)
print(q,'\n')

[0 1 2 3 4 5 6 7 8] 

[ 9 10 11 12 13 14 15 16 17] 

[ 9.  10.5 12.  13.5 15.  16.5] 



In [146]:
s=np.arange(10)
print(s,type(s))        

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [151]:
s=np.arange(10)
print('Los números mayores a 3, serán multiplicados por 3:',s)
s[s>3]=s[s>3]*3
print(s)

Los números mayores a 3, serán multiplicados por 3: [0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 12 15 18 21 24 27]


## DIFERENTES TIPOS DE MATRICES BIDIMENSIONALES


In [60]:
e=np.ones([3,6])*2
print(e)
e=np.ones((3,5))*100
print(e)

[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]
[[100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]]


In [61]:
w=np.ones(6)
print(w,'\n')
print(w.dtype,'\n')
a=np.ones(6,dtype='int32')
print(a.dtype,'\n')
print('--------------------------------------------------------------')
p=np.ones((5,6),dtype=int)
print(p,'\n')
print(p.dtype,'\n')

[1. 1. 1. 1. 1. 1.] 

float64 

int32 

--------------------------------------------------------------
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

int32 



In [ ]:
w=np.zeros(8)
print(w,'\n')
print(w.dtype,'\n')
a=np.zeros(8,dtype='int32')
print(a.dtype,'\n')
print('--------------------------------------------------------------')
p=np.zeros((5,6))
print(p,'\n')
print(p.dtype,'\n')

In [63]:
r=np.full([5,7],100)
print(r)

[[100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]]


In [15]:
n2=np.full([4,8],5)
print(n2)

[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


In [23]:
matriz=np.identity(5); print('MATRIZ IDENTIDAD')
print(matriz,'\n')
matriz2=np.ones([10,10])
matriz2[1:9,1:9]=0
print(matriz2)

MATRIZ IDENTIDAD
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [31]:
s1=np.arange(1,26).reshape(5,5)
s2=np.random.randint(3,8,25).reshape(5,5)
m=np.diag([1,2,3,4,5])
print(m)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [65]:
s=np.zeros(16).reshape(4,4)
s[::2,1::2]=1
s[1::2,::2]=1
print(s)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


## PRODUCTO PUNTO O ESCALAR

In [67]:
a=np.array([1,2,3])
b=np.array([0.1,2,0.3])
print(a@b)
print(np.dot(a,b))

5.0
5.0


## CREANDO MATRICES TRIDIMENSIONALES

In [54]:
a=np.random.random((4,2,3))
print(a)
print(a.ndim)
print(a.shape)

[[[0.68976576 0.53812406 0.51583157]
  [0.15673708 0.78237152 0.84174235]]

 [[0.1837956  0.1577391  0.14695851]
  [0.20707744 0.75628152 0.78450778]]

 [[0.88132672 0.22681818 0.40785545]
  [0.60596437 0.46008627 0.28257006]]

 [[0.55247775 0.5268758  0.69163322]
  [0.42028637 0.09695336 0.7293751 ]]]
3
(4, 2, 3)


## LINSPACE Y LONGSPACE

In [126]:
w=np.linspace(10,50,5); print('5 VALORES ESPACIADOS ENTRE EL 10 Y 50:')
print(w)

5 VALORES ESPACIADOS ENTRE EL 10 Y 50:
[10. 20. 30. 40. 50.]


In [65]:
e=np.linspace(0,6,5)
print(e,'\n')
u=np.linspace(0,6,5,dtype=int)
print(u)

[0.  1.5 3.  4.5 6. ] 

[0 1 3 4 6]


In [66]:
e=np.logspace(0,1,5)
print(e,'\n')
u=np.logspace(0,1,5,dtype=int)
print(u,'\n')
t=np.logspace(0,1,5,base=2)
print(t)

[ 1.          1.77827941  3.16227766  5.62341325 10.        ] 

[ 1  1  3  5 10] 

[1.         1.18920712 1.41421356 1.68179283 2.        ]


## OPERACIONES CON LOS ' ndarrays '

In [67]:
# REGLAS DE DIFUSIÓN
# REGLA N°1:

r=np.array([2,3,5])
p=np.array([2,6,1]) # p=np.array([2,6])
s=r+p
print(s,'\n')
y=np.array([3])
d=r+y
print(d,'\n')
d=np.array([2,3,5]) + 3
print(d)

[4 9 6] 

[5 6 8] 

[5 6 8]


In [76]:
# REGLA N°2:

a=np.array([1,2,3,4,5])
b=np.array([10,11,12,13,14])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(b**a)

[11 13 15 17 19]
[-9 -9 -9 -9 -9]
[10 22 36 52 70]
[0.1        0.18181818 0.25       0.30769231 0.35714286]
[    10    121   1728  28561 537824]


In [80]:
a=np.arange(1,13).reshape(4,3)
b=np.array([10,10,10])
print(a,'\n')
print(b,'\n')
print(np.add(a,b),'\n')
print(np.subtract(a,b),'\n')
print(np.multiply(a,b),'\n')
print(np.divide(a,b),'\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[10 10 10] 

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]] 

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]] 

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]] 

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [1.  1.1 1.2]] 



In [27]:
a=np.arange(5,13)
print(a)
s=slice(2,9,2)
print(a[s])

[ 5  6  7  8  9 10 11 12]
[ 7  9 11]


In [40]:
a=np.arange(5,20)
print(a)
print(np.split(a,[5,8]))

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[array([5, 6, 7, 8, 9]), array([10, 11, 12]), array([13, 14, 15, 16, 17, 18, 19])]


In [47]:
s=np.arange(1,13)
print(s)
s=s.reshape(2,6)
print('\n',s,'\n')
s1=np.resize(s,(3,3))
s2=np.resize(s,(5,10))
print('\n',s1,'\n')
print(s2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 


 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12  1  2  3  4  5  6  7  8]
 [ 9 10 11 12  1  2  3  4  5  6]
 [ 7  8  9 10 11 12  1  2  3  4]
 [ 5  6  7  8  9 10 11 12  1  2]]


## MÉTODOS MUY SIMILARES A LOS STRINGS CON NUMPY

In [46]:
# SOLO ES APLICABLE PARA ESCALARES
print(np.add(1,3))
print(np.subtract(3,1))
print(np.multiply(5,6))
print(np.divide(18,9))

# APLICABLE PARA DATOS DE TIPO STRING
s=np.char.add(['hola',' mundo.'],['QUE TAL',' :)'])
print('\n',s,' -> ',s.shape,'\t',s.ndim)

print('\n',np.char.multiply('ohhhh',4))

c=' BIENVENIDOS '
print('\n',np.char.center(c,len(c)+20,fillchar='-'))

x2=np.char.lower(['JOSE','MARIA'])
print('\n',x2)

x3=np.char.lower('RAUL')
print('\n',x3,' -> ',x3.ndim)

x4=np.char.split('hola, no pense que vendrías por acá!!!')
print('\n',x4,' -> ' ,type(x4))

x5=np.char.splitlines('hola\n no pense que vendrías por acá!!!')
print('\n',x5,' -> ' ,type(x5),)

x6=np.char.strip(['nina','josefina','manzana'],'a')
print('\n',x6,' -> ' ,type(x6),)

x7=np.char.join([':','-'],['dmy','ymd'])
print('\n',x7,' -> ' ,type(x7),)

x8=np.char.replace('Eres un buen ingeniero','ingeniero','bailarín')
print('\n',x8,' -> ' ,type(x8),)

4
2
30
2.0

 ['holaQUE TAL' ' mundo. :)']  ->  (2,) 	 1

 ohhhhohhhhohhhhohhhh

 ---------- BIENVENIDOS ----------

 ['jose' 'maria']

 raul  ->  0

 ['hola,', 'no', 'pense', 'que', 'vendrías', 'por', 'acá!!!']  ->  <class 'numpy.ndarray'>

 ['hola', ' no pense que vendrías por acá!!!']  ->  <class 'numpy.ndarray'>

 ['nin' 'josefin' 'manzan']  ->  <class 'numpy.ndarray'>

 ['d:m:y' 'y-m-d']  ->  <class 'numpy.ndarray'>

 Eres un buen bailarín  ->  <class 'numpy.ndarray'>


In [76]:
s=np.arange(1,13).reshape(4,3)
v=np.array([1,1,0])
print(s)
m=np.empty_like(s)
for i in range(4):
    m[i,:]=m[i,:]+v
print('\n',m)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


In [78]:
s=np.array([1,2,3])
print(s)
print(type(s))
lista=s.tolist()
print('\n',lista)
print(type(lista))

[1 2 3]
<class 'numpy.ndarray'>

 [1, 2, 3]
<class 'list'>


## UNIENDO MATRICES

In [73]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
e=np.vstack((n1,n2))
print(e,'\n')
print(np.concatenate([n1,n2]))


[[10 20 30]
 [40 50 60]] 

[10 20 30 40 50 60]


In [80]:
s=np.random.randint(10,size=(2,10))
print(s) 
b=np.hsplit(s,2)
b

[[3 4 7 6 4 0 0 8 4 8]
 [4 1 8 7 9 7 2 1 3 2]]


[array([[3, 4, 7, 6, 4],
        [4, 1, 8, 7, 9]]),
 array([[0, 0, 8, 4, 8],
        [7, 2, 1, 3, 2]])]

In [70]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
e=np.hstack((n1,n2))
print(e)

[10 20 30 40 50 60]


In [72]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
e=np.column_stack((n1,n2))
print(e)

[[10 40]
 [20 50]
 [30 60]]


In [26]:
n1=np.array([[1,2,0],[3,4,8]])
n2=np.array([[5,6,0],[7,8,9]])
print(np.concatenate((n1,n2)))
print('\n',np.concatenate((n1,n2),axis=0),'\n')
print(np.concatenate((n1,n2),axis=1))

[[1 2 0]
 [3 4 8]
 [5 6 0]
 [7 8 9]]

 [[1 2 0]
 [3 4 8]
 [5 6 0]
 [7 8 9]] 

[[1 2 0 5 6 0]
 [3 4 8 7 8 9]]


## INTERSECCIÓN Y DIFERENCIA

In [72]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
p1=np.intersect1d(n1,n2)
p2=np.setdiff1d(n1,n2)
p3=np.setdiff1d(n2,n1)
print(p1,'\n')
print(p2,'\n')
print(p3,'\n')

[50 60] 

[10 20 30 40] 

[70 80 90] 



## MEDIA, MEDIA Y DESVIACIÓN ESTANDAR DE DATOS

In [49]:
x=np.array([10,20,30,40])
x1=np.mean(x)
x2=np.sqrt(x)
x3=np.log(x)
x4=np.log10(x)
print(x1)
print(x2)
print(x3)
print(x4)

25.0
[3.16227766 4.47213595 5.47722558 6.32455532]
[2.30258509 2.99573227 3.40119738 3.68887945]
[1.         1.30103    1.47712125 1.60205999]


In [ ]:
y=np.array([5,2,8,5,6,7,1,2])
y1=np.median(y)
print(y1,'\n')
y2=np.std(y) # desviacion estandar = sqrt(varianza)
print(y2)

In [70]:
y=np.array([5,2,8,5,6,7,1,2])
w=np.transpose(y)
a=np.resize(w,[6,5])
a.sort(axis=1)
print(a)

[[2 5 5 6 8]
 [1 2 2 5 7]
 [1 5 6 7 8]
 [2 2 5 5 8]
 [1 2 5 6 7]
 [2 5 6 7 8]]


In [ ]:
# MULTIPLICACION DE MATRICES
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n1,'\n')
n2=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(n2,'\n')
u1=n1.dot(n2)
u2=n2.dot(n1)
print(u1,'\n')
print(u2,'\n')


In [ ]:
a=np.ones((5,6))
print(a,'\n')
print(a.shape,'\n')
print(a.sum(),'\n')
b=a.sum(axis=0)
print(b,'\n')
print(b.shape,'\n')
c=a.sum(axis=1)
print(c,'\n')
print(c.shape,'\n')



In [51]:
# https://docs.scipy.org/doc/numpy-1.17.0/numpy-ref-1.17.0.pdf
# https://numpy.org/doc/stable/reference/
# https://material-docente.gitbook.io/parte-practica-informatica-para-ingenieria/practica-6.-matrices.-conjuntos/matrices-suma-y-multiplicacion

In [7]:
x=np.genfromtxt('data.txt',delimiter=',',dtype='int32')
print(x)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [14]:
print(x>50)

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


In [11]:
print(x[x>50])

[196  75 766  75  55 999  78  76  88]


In [16]:
print(x)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [17]:
a=np.any(x>50,axis=0)
print(a)

[False False False False  True  True False  True  True False False False
 False False False False  True  True]


In [18]:
b=np.all(x>50,axis=0)
print(b)

[False False False False  True False False False False False False False
 False False False False False False]


In [1]:
print(x[~((x>5) & (x<8))])

NameError: name 'x' is not defined

In [22]:
colegios=np.array(['san_gregorio','san_isidro','talent','innova','trilce','pamer'])
departamento=np.array(['lima','cuzco','ucayali','lima','cuzco','puno'])
mensualidad=np.array([320,480,280,500,409,720])
precio_prom=np.mean(mensualidad)
vbool=mensualidad>precio_prom
print(colegios[vbool])

['san_isidro' 'innova' 'pamer']


In [29]:
for i in np.icolegios:
    print(i)

san_gregorio
san_isidro
talent
innova
trilce
pamer


In [28]:
cole=input('infrese el departamento:')
x=departamento==cole
print(colegios[x])
print(np.sum(x))

infrese el departamento:puno
['pamer']
1


In [23]:
men_cuzco=(mensualidad[departamento=='cuzco'])>=precios_lima_prom
print(men_cuzco)

[ True False]


In [24]:
print(mensualidad[departamento=='cuzco'])
print(colegios[departamento=='cuzco'])
print(colegios[departamento=='cuzco'][men_cuzco])

[480 409]
['san_isidro' 'trilce']
['san_isidro']
